on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  create:
  workflow_dispatch:
  schedule:
    - cron: "30 */12 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: write-all

env:
  ZEPHYR_SDK_VERSION: "0.17.4"

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:

      - name: 💻 Checkout Repository
        if: always()
        uses: actions/checkout@v5

      - name: 📝 Put Commit Hash/Name in Env Variables
        if: always()
        run: |
          echo "GIT_HASH=$(git rev-parse --short=8 HEAD)" >> $GITHUB_ENV
          echo "GIT_MESSAGE<<EOF" >> $GITHUB_ENV
          git log -1 --pretty=%B >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: 💻 Checkout Repository
        if: always()
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: 🏷️ Generate Tag
        if: always()
        run: |
          echo "TAG_NAME=daily-$(date -u +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: 🏷️ Create or Update Tag
        if: always()
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git tag -f "${TAG_NAME}"
          git push -f origin "${TAG_NAME}"

      - name: ⏱️ Generate Timestamp
        if: always()
        run: |
          echo "RUN_TIMESTAMP=$(date -u +'%Y%m%dT%H%M%SZ')" >> $GITHUB_ENV

      - name: 🧹 Clean Landing Site
        if: always()
        run: |
          sudo rm -rf zephyr-workspace/SlimeNRF-CI
      - uses: actions/checkout@v5
        with:
          path: zephyr-workspace/SlimeNRF-CI

      - name: 🧰 Cache + Install apt Dependencies
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: >-
            git cmake ninja-build gperf dfu-util device-tree-compiler wget
            python3-dev python3-pip python3-setuptools python3-tk python3-wheel python3-venv
            xz-utils file make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1
          version: 1.0

      - name: 📦 Cache Zephyr SDK
        id: cache-sdk
        uses: actions/cache@v4
        with:
          path: ~/zephyr-sdk
          key: zephyr-sdk-${{ env.ZEPHYR_SDK_VERSION }}

      - name: 🪁 Install Zephyr SDK
        if: steps.cache-sdk.outputs.cache-hit != 'true'
        run: |
          wget -q -O zephyr-sdk_linux-x86_64_minimal.tar.xz https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v${{ env.ZEPHYR_SDK_VERSION }}/zephyr-sdk-${{ env.ZEPHYR_SDK_VERSION }}_linux-x86_64_minimal.tar.xz
          tar xf zephyr-sdk_linux-x86_64_minimal.tar.xz -C ~/
          rm -rf ~/zephyr-sdk
          mv ~/zephyr-sdk-*/ ~/zephyr-sdk
          ~/zephyr-sdk/setup.sh -c -t arm-zephyr-eabi

      - name: 📦 Cache West Workspace
        id: cache-west
        uses: actions/cache@v4
        with:
          path: zephyr-workspace
          submodules: recursive
          key: west-workspace-${{ env.TAG_NAME }}

      - name: 📦 Cache Python Venv
        id: cache-venv
        uses: actions/cache@v4
        with:
          path: ~/.venv
          key: venv-${{ hashFiles('zephyr-workspace/zephyr/scripts/requirements.txt') }}

      - name: 🐍 Setup Python Venv + West
        if: steps.cache-venv.outputs.cache-hit != 'true'
        run: |
          python3 -m venv ~/.venv
          ~/.venv/bin/pip install west ninja

      - name: 📦 Cache PIP Requirements
        id: cache-pip
        uses: actions/cache@v4
        with:
          path: ~/.venv
          key: venv-pip-${{ hashFiles('zephyr-workspace/zephyr/scripts/requirements.txt') }}

      - name: 🐍 Install Zephyr Python Requirements
        if: steps.cache-pip.outputs.cache-hit != 'true'
        run: |
          cd zephyr-workspace
          ~/.venv/bin/pip install -r zephyr/scripts/requirements.txt

  build:
    needs: setup
    continue-on-error: true
    strategy:
      fail-fast: false
      matrix:
        boards: [
                  {filename: "SlimeNRF_Tracker_SPI_ProMicro", fileformat: "uf2", boardname: "promicro_uf2/nrf52840/spi", type: "tracker", repository_url: "https://github.com/SlimeVR/SlimeVR-Tracker-nRF.git", repository_revision: "main", sdk_url: "https://github.com/nrfconnect/sdk-nrf.git", sdk_revision: "v3.1.1", vqf_url: "https://github.com/sctanf/vqf-c.git", vqf_repository: "master", clk: "disabled", extraaction: "enabled",  magnetometer: "disabled", sleep: "enabled", sw0: "disabled"}, 
                  {filename: "SlimeNRF_Tracker_NoSleep_SPI_StackedSmol", fileformat: "uf2", boardname: "promicro_uf2/nrf52840/spi", type: "tracker", repository_url: "https://github.com/LyallUlric/Stacked-SmolSlime.git", repository_revision: "main", sdk_url: "https://github.com/nrfconnect/sdk-nrf.git", sdk_revision: "v3.1.1", vqf_url: "https://github.com/sctanf/vqf-c.git", vqf_repository: "master", clk: "enabled", extraaction: "enabled",  magnetometer: "disabled", sleep: "disabled", sw0: "enabled"}, 
                  {filename: "SlimeNRF_Tracker_TDMA_SPI_ProMicro", fileformat: "uf2", boardname: "promicro_uf2/nrf52840/spi", type: "tracker", repository_url: "https://github.com/SlimeVR/SlimeVR-Tracker-nRF.git", repository_revision: "tdma", sdk_url: "https://github.com/SlimeVR/sdk-nrf.git", sdk_revision: "slime-esb", vqf_url: "https://github.com/sctanf/vqf-c.git", vqf_repository: "master", clk: "disabled", extraaction: "enabled",  magnetometer: "disabled", sleep: "enabled", sw0: "disabled"}, 
                  {filename: "SlimeNRF_Tracker_Mag_NoSleep_SPI_ProMicro_JitingCat", fileformat: "uf2", boardname: "promicro_uf2/nrf52840/default_spi", type: "tracker", repository_url: "https://github.com/jitingcn/SlimeVR-Tracker-nRF.git", repository_revision: "dev", sdk_url: "https://github.com/nrfconnect/sdk-nrf.git", sdk_revision: "v3.1.0", vqf_url: "https://github.com/sctanf/vqf-c.git", vqf_repository: "cmsis-dsp-optimization", clk: "enabled", extraaction: "enabled",  magnetometer: "N/A", sleep: "disabled", sw0: "enabled"}, 
                ]
    if: always()
    runs-on: ubuntu-latest
    steps:

      - name: 💻 Checkout Repository
        if: always()
        uses: actions/checkout@v5
        with:
          path: zephyr-workspace/SlimeNRF-CI
          submodules: recursive

      - name: 🧰 Cache + Install Apt Dependencies
        if: always()
        uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: >-
            git cmake ninja-build gperf dfu-util device-tree-compiler wget
            python3-dev python3-pip python3-setuptools python3-tk python3-wheel python3-venv
            xz-utils file make gcc gcc-multilib g++-multilib libsdl2-dev libmagic1
          version: 1.0

      - name: 📦 Restore Zephyr SDK
        if: always()
        uses: actions/cache/restore@v4
        with:
          path: ~/zephyr-sdk
          key: zephyr-sdk-${{ env.ZEPHYR_SDK_VERSION }}
          fail-on-cache-miss: true

      - name: 🪁 Register Zephyr SDK
        if: always()
        run: |
          ~/zephyr-sdk/setup.sh -c -t arm-zephyr-eabi

      - name: 📦 Restore West Workspace
        if: always()
        uses: actions/cache/restore@v4
        with:
          path: zephyr-workspace
          submodules: recursive
          key: west-workspace-${{ env.TAG_NAME }}
          fail-on-cache-miss: true

      - name: 📦 Restore Python Venv
        if: always()
        uses: actions/cache/restore@v4
        with:
          path: ~/.venv
          key: venv-pip-${{ hashFiles('zephyr-workspace/zephyr/scripts/requirements.txt') }}
          restore-keys: |
            venv-pip-
            venv-
          fail-on-cache-miss: true

      - name: 📦 Restore Zephyr Workspace
        id: zephyr-cache
        uses: actions/cache@v4
        with:
          path: zephyr-workspace
          submodules: recursive
          key: zephyr-${{ env.RUN_TIMESTAMP }}-${{ matrix.boards.repository_url }}-${{ matrix.boards.repository_revision }}
          fail-on-cache-miss: false

      - name: ♻️ Initialize Zephyr Workspace
        if: steps.zephyr-cache.outputs.cache-hit != 'true'
        run: |
          sed -i '/- name:[[:space:]]*SlimeVR-Tracker-nRF/,/revision:/ { s|url:[[:space:]]*.*|url: ${{ matrix.boards.repository_url }}|; s|revision:[[:space:]]*.*|revision: ${{ matrix.boards.repository_revision }}|; } ; /- name:[[:space:]]*sdk-nrf/,/import:/ { s|url:[[:space:]]*.*|url: ${{ matrix.boards.sdk_url }}|; s|revision:[[:space:]]*.*|revision: ${{ matrix.boards.sdk_revision }}|; } ; /- name:[[:space:]]*vqf-c/,/revision:/ { s|url:[[:space:]]*.*|url: ${{ matrix.boards.vqf_url }}|; s|revision:[[:space:]]*.*|revision: ${{ matrix.boards.vqf_revision }}|; }' west.yml
          sed -i '/- name:[[:space:]]*SlimeVR-Tracker-nRF/,/revision:/ { s|url:[[:space:]]*.*|url: ${{ matrix.boards.repository_url }}|; s|revision:[[:space:]]*.*|revision: ${{ matrix.boards.repository_revision }}|; } ; /- name:[[:space:]]*sdk-nrf/,/import:/ { s|url:[[:space:]]*.*|url: ${{ matrix.boards.sdk_url }}|; s|revision:[[:space:]]*.*|revision: ${{ matrix.boards.sdk_revision }}|; } ; /- name:[[:space:]]*vqf-c/,/revision:/ { s|url:[[:space:]]*.*|url: ${{ matrix.boards.vqf_url }}|; s|revision:[[:space:]]*.*|revision: ${{ matrix.boards.vqf_revision }}|; }' zephyr-workspace/SlimeNRF-CI/west.yml
          cd zephyr-workspace
          sudo rm -rf .west
          west init -l SlimeNRF-CI
          west update --narrow -o=--depth=1
          west zephyr-export

      - name: 📦 Cache Zephyr Workspace
        if: steps.zephyr-cache.outputs.cache-hit != 'true'
        uses: actions/cache@v4
        with:
          path: zephyr-workspace
          submodules: recursive
          key: zephyr-${{ env.RUN_TIMESTAMP }}-${{ matrix.boards.repository_url }}-${{ matrix.boards.repository_revision }}

      - name: 🔧 Preparing Build Environment
        if: always()
        run: |
          cd zephyr-workspace
          sudo rm -rf Releases
          mkdir Releases

      - name: 🔧 Disabling External Clock
        if: ${{ (matrix.boards.type == 'tracker') && (matrix.boards.clk == 'disabled') }}
        run: |
          cd zephyr-workspace
          find='clk-gpios[ \t]='
          replace='// clk-gpios ='
          sed -i "s|$find|$replace|g" SlimeVR-Tracker-nRF/boards/nordic/promicro_uf2/promicro_uf2.dts
          sed -i "s|$find|$replace|g" SlimeVR-Tracker-nRF/boards/xiao_ble.overlay
          sed -i "s|$find|$replace|g" SlimeVR-Tracker-nRF/boards/xiao_ble_nrf52840_sense.overlay
          printf "\n\nCONFIG_USE_SENSOR_CLOCK=n" >> SlimeVR-Tracker-nRF/prj.conf

      - name: 🔧 Enabling External Clock
        if: ${{ (matrix.boards.type == 'tracker') && (matrix.boards.clk == 'enabled') }}
        run: |
          cd zephyr-workspace
          find="\/\/\sclk-gpios"
          replace="clk-gpios"
          sed -i "s/$find/$replace/g" SlimeVR-Tracker-nRF/boards/nordic/promicro_uf2/promicro_uf2.dts
          sed -i "s/$find/$replace/g" SlimeVR-Tracker-nRF/boards/xiao_ble.overlay
          printf "\n\nCONFIG_USE_SENSOR_CLOCK=y" >> SlimeVR-Tracker-nRF/prj.conf

      - name: 🔧 Disabling Extra Action
        if: ${{ (matrix.boards.type == 'tracker') && (matrix.boards.extraaction == 'disabled') }}
        run: |
          cd zephyr-workspace
          printf "\n\nCONFIG_USER_EXTRA_ACTIONS=n" >> SlimeVR-Tracker-nRF/prj.conf

      - name: 🔧 Enabling Extra Action
        if: ${{ (matrix.boards.type == 'tracker') && (matrix.boards.extraaction == 'enabled') }}
        run: |
          cd zephyr-workspace
          printf "\n\nCONFIG_USER_EXTRA_ACTIONS=y" >> SlimeVR-Tracker-nRF/prj.conf

      - name: 🔧 Disabling Magnetometer
        if: ${{ (matrix.boards.type == 'tracker') && (matrix.boards.magnetometer == 'disabled') }}
        run: |
          cd zephyr-workspace
          printf "\n\nCONFIG_SENSOR_USE_MAG=n" >> SlimeVR-Tracker-nRF/prj.conf

      - name: 🔧 Enabling Magnetometer
        if: ${{ (matrix.boards.type == 'tracker') && (matrix.boards.magnetometer == 'enabled') }}
        run: |
          cd zephyr-workspace
          printf "\n\nCONFIG_SENSOR_USE_MAG=y" >> SlimeVR-Tracker-nRF/prj.conf

      - name: 🔧 Disabling Sleep
        if: ${{ (matrix.boards.type == 'tracker') && (matrix.boards.sleep == 'disabled') }}
        run: |
          cd zephyr-workspace
          printf "\n\nCONFIG_USE_IMU_WAKE_UP=n" >> SlimeVR-Tracker-nRF/prj.conf
          printf "\n\nCONFIG_USE_ACTIVE_TIMEOUT=n" >> SlimeVR-Tracker-nRF/prj.conf
          printf "\n\nCONFIG_SENSOR_LP_TIMEOUT=300000" >> SlimeVR-Tracker-nRF/prj.conf
          printf "\n\nCONFIG_SENSOR_USE_LOW_POWER_2=n" >> SlimeVR-Tracker-nRF/prj.conf

      - name: 🔧 Enabling Sleep
        if: ${{ (matrix.boards.type == 'tracker') && (matrix.boards.sleep == 'enabled') }}
        run: |
          cd zephyr-workspace
          printf "\n\nCONFIG_USE_IMU_WAKE_UP=y" >> SlimeVR-Tracker-nRF/prj.conf
          printf "\n\nCONFIG_USE_ACTIVE_TIMEOUT=y" >> SlimeVR-Tracker-nRF/prj.conf
  

      - name: 🔧 Disabling SW0 Button
        if: ${{ (matrix.boards.type == 'tracker') && (matrix.boards.sw0 == 'disabled') }}
        run: |
          cd zephyr-workspace
          find='sw0[ \t]='
          replace='// sw0 ='
          sed -i "s|$find|$replace|g" SlimeVR-Tracker-nRF/boards/nordic/promicro_uf2/promicro_uf2.dts
          sed -i "s|$find|$replace|g" SlimeVR-Tracker-nRF/boards/xiao_ble.overlay
          sed -i "s|$find|$replace|g" SlimeVR-Tracker-nRF/boards/xiao_ble_nrf52840_sense.overlay

      - name: 🔧 Enabling SW0 Button
        if: ${{ (matrix.boards.type == 'tracker') && (matrix.boards.sw0 == 'enabled') }}
        run: |
          cd zephyr-workspace
          find='\/\/\ssw0\s='
          replace='sw0 ='
          sed -i "s/$find/$replace/g" SlimeVR-Tracker-nRF/boards/nordic/promicro_uf2/promicro_uf2.dts
          sed -i "s/$find/$replace/g" SlimeVR-Tracker-nRF/boards/xiao_ble.overlay
          sed -i "s/$find/$replace/g" SlimeVR-Tracker-nRF/boards/xiao_ble_nrf52840_sense.overlay

      - name: 🔨 Stacked Prep
        if: ${{ (matrix.boards.type == 'tracker') && (contains(matrix.boards.filename, 'Stacked')) }}
        run: |
          cd zephyr-workspace
          printf "\n\nCONFIG_SENSOR_USE_6_SIDE_CALIBRATION=y" >> SlimeVR-Tracker-nRF/prj.conf
          sudo rm -f SlimeVR-Tracker-nRF/boards/nordic/promicro_uf2/board.c
          curl -fSL https://raw.githubusercontent.com/Shine-Bright-Meow/SlimeNRF-Tracker/stacked-variant/pm_static_promicro_uf2_nrf52840_stackedi2c.yml -o SlimeVR-Tracker-nRF/pm_static_promicro_uf2_nrf52840_stackedi2c.yml
          curl -fSL https://raw.githubusercontent.com/Shine-Bright-Meow/SlimeNRF-Tracker/stacked-variant/pm_static_promicro_uf2_nrf52840_stackedspi.yml -o SlimeVR-Tracker-nRF/pm_static_promicro_uf2_nrf52840_stackedspi.yml
          curl -fSL https://raw.githubusercontent.com/Shine-Bright-Meow/SlimeNRF-Tracker/stacked-variant/socs/nrf52840_stackedi2c.overlay -o SlimeVR-Tracker-nRF/socs/nrf52840_stackedi2c.overlay
          curl -fSL https://raw.githubusercontent.com/Shine-Bright-Meow/SlimeNRF-Tracker/stacked-variant/socs/nrf52840_stackedspi.overlay -o SlimeVR-Tracker-nRF/socs/nrf52840_stackedspi.overlay
          curl -fSL https://raw.githubusercontent.com/Shine-Bright-Meow/SlimeNRF-Tracker/stacked-variant/boards/nordic/promicro_uf2/promicro_uf2_stackedi2c.yaml -o SlimeVR-Tracker-nRF/boards/nordic/promicro_uf2/promicro_uf2_stackedi2c.yaml
          curl -fSL https://raw.githubusercontent.com/Shine-Bright-Meow/SlimeNRF-Tracker/stacked-variant/boards/nordic/promicro_uf2/promicro_uf2_stackedi2c_defconfig -o SlimeVR-Tracker-nRF/boards/nordic/promicro_uf2/promicro_uf2_stackedi2c_defconfig
          curl -fSL https://raw.githubusercontent.com/Shine-Bright-Meow/SlimeNRF-Tracker/stacked-variant/boards/nordic/promicro_uf2/promicro_uf2_stackedspi.yaml -o SlimeVR-Tracker-nRF/boards/nordic/promicro_uf2/promicro_uf2_stackedspi.yaml
          curl -fSL https://raw.githubusercontent.com/Shine-Bright-Meow/SlimeNRF-Tracker/stacked-variant/boards/nordic/promicro_uf2/promicro_uf2_stackedspi_defconfig -o SlimeVR-Tracker-nRF/boards/nordic/promicro_uf2/promicro_uf2_stackedspi_defconfig
          curl -fSL https://raw.githubusercontent.com/Shine-Bright-Meow/SlimeNRF-Tracker/stacked-variant/boards/nordic/promicro_uf2/promicro_uf2_stackedi2c.dts -o SlimeVR-Tracker-nRF/boards/nordic/promicro_uf2/promicro_uf2_stackedi2c.dts
          curl -fSL https://raw.githubusercontent.com/Shine-Bright-Meow/SlimeNRF-Tracker/stacked-variant/boards/nordic/promicro_uf2/promicro_uf2_stackedspi.dts -o SlimeVR-Tracker-nRF/boards/nordic/promicro_uf2/promicro_uf2_stackedspi.dts
          curl -fSL https://raw.githubusercontent.com/Shine-Bright-Meow/SlimeNRF-Tracker/stacked-variant/boards/nordic/promicro_uf2/board.yml -o SlimeVR-Tracker-nRF/boards/nordic/promicro_uf2/board.yml
          curl -fSL https://raw.githubusercontent.com/Shine-Bright-Meow/SlimeNRF-Tracker/stacked-variant/boards/nordic/promicro_uf2/board.c -o SlimeVR-Tracker-nRF/boards/nordic/promicro_uf2/board.c

      - name: 🔨 Build SlimeVR-Tracker-nRF - ${{ matrix.boards.boardname }}
        if: always()
        run: |
          cd zephyr-workspace
          sudo rm -rf SlimeVR-Tracker-nRF/build
          mkdir SlimeVR-Tracker-nRF/build

          west build \
              --board ${{ matrix.boards.boardname }} \
              --pristine=always SlimeVR-Tracker-nRF \
              --build-dir SlimeVR-Tracker-nRF/build \
              -- \
              -DNCS_TOOLCHAIN_VERSION=NONE \
              -DBOARD_ROOT=../SlimeVR-Tracker-nRF

          mv SlimeVR-Tracker-nRF/build/SlimeVR-Tracker-nRF/zephyr/zephyr.${{ matrix.boards.fileformat }} Releases/${{ matrix.boards.filename }}.${{ matrix.boards.fileformat }}


      - name: 💾 Upload Artifact - ${{ matrix.boards.boardname }}
        if: always()
        uses: actions/upload-artifact@v5
        with:
          name: ${{ matrix.boards.filename }}.${{ matrix.boards.fileformat }}
          path: zephyr-workspace/Releases/${{ matrix.boards.filename }}.${{ matrix.boards.fileformat }}

      - name: 📁 Create/Update Github Latest Release
        if: always()
        uses: mini-bomba/create-github-release@v1.2.0
        with:
          token: ${{ secrets.gh_token }}
          tag: "latest"
          prerelease: false
          name: "Latest Firmware"
          body: |
            Latest successful SlimeNRF Firmware build. (Automated)
          files: |
            zephyr-workspace/Releases/${{ matrix.boards.filename }}.${{ matrix.boards.fileformat }}
          clear_attachments: false

      - name: 📁 Create/Update Github Daily Release
        if: always()
        uses: mini-bomba/create-github-release@v1.2.0
        with:
          token: ${{ secrets.gh_token }}
          tag: "${{ env.TAG_NAME }}"
          prerelease: true
          name: "${{ env.TAG_NAME }}"
          body: |
            Archive of successful daily SlimeNRF Firmware build. (Automated)
          files: |
            zephyr-workspace/Releases/${{ matrix.boards.filename }}.${{ matrix.boards.fileformat }}
          clear_attachments: false
